# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: myapp
    - run: npm run build --if-present
      working-directory: myapp
    - run: npm test
      working-directory: myapp
    - name: Login to Heroku Container registry
      env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
      working-directory: myapp 
    - run: npm test
      working-directory: myapp
    - name: heroku deploy
      uses: akhileshns/heroku-deploy@v3.6.8
      with:
           heroku_api_key: ${{secrets.HEROKU_API_KEY}}
           heroku_app_name: "ammar-name"
           heroku_email: "ammarahmad749@gmail.com"
           appdir: "myapp"
           buildpack: https://github.com/heroku/heroku-buildpack-nodejs#v170
   # - run: npm test -- --coverage
   #   working-directory: myapp
   # - run: bash <(curl -s https://codecov.io/bash)
    - uses: actions/checkout@master
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        file: ./coverage.xml # optional
        files: ./coverage1.xml,./coverage2.xml # optional
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)

  
